// Maps nationality names (as used by our team/player data) to flagcdn.com country codes.
const COUNTRY_CODES: Record<string, string> = {
  Albania: 'al',
  Algeria: 'dz',
  Angola: 'ao',
  Argentina: 'ar',
  Armenia: 'am',
  Australia: 'au',
  Austria: 'at',
  Belgium: 'be',
  Benin: 'bj',
  'Bosnia-Herzegovina': 'ba',
  Brazil: 'br',
  'Burkina Faso': 'bf',
  Cameroon: 'cm',
  Canada: 'ca',
  'Cape Verde': 'cv',
  'Central African Republic': 'cf',
  Chad: 'td',
  Chile: 'cl',
  Colombia: 'co',
  Comoros: 'km',
  Congo: 'cg',
  'Costa Rica': 'cr',
  "Cote d'Ivoire": 'ci',
  Croatia: 'hr',
  'Czech Republic': 'cz',
  'DR Congo': 'cd',
  Denmark: 'dk',
  'Dominican Republic': 'do',
  Egypt: 'eg',
  England: 'gb-eng',
  Ecuador: 'ec',
  'Equatorial Guinea': 'gq',
  Finland: 'fi',
  France: 'fr',
  'French Guiana': 'fr',
  Gabon: 'ga',
  Georgia: 'ge',
  Germany: 'de',
  Ghana: 'gh',
  Greece: 'gr',
  Guadeloupe: 'fr',
  'Guinea-Bissau': 'gw',
  Guatemala: 'gt',
  Guinea: 'gn',
  Haiti: 'ht',
  Hungary: 'hu',
  Iceland: 'is',
  Indonesia: 'id',
  Ireland: 'ie',
  Israel: 'il',
  Italy: 'it',
  Jamaica: 'jm',
  Japan: 'jp',
  Kosovo: 'xk',
  'Korea, South': 'kr',
  Lithuania: 'lt',
  Macedonia: 'mk',
  Madagascar: 'mg',
  Mali: 'ml',
  Martinique: 'fr',
  Mauritania: 'mr',
  Mexico: 'mx',
  Moldova: 'md',
  Montenegro: 'me',
  Morocco: 'ma',
  Mozambique: 'mz',
  Netherlands: 'nl',
  Neukaledonien: 'nc',
  'New Caledonia': 'nc',
  'New Zealand': 'nz',
  Nigeria: 'ng',
  'North Macedonia': 'mk',
  'Northern Ireland': 'gb-nir',
  Norway: 'no',
  Paraguay: 'py',
  Philippines: 'ph',
  Poland: 'pl',
  Portugal: 'pt',
  Romania: 'ro',
  Réunion: 're',
  Scotland: 'gb-sct',
  Senegal: 'sn',
  Serbia: 'rs',
  'Serbia and Montenegro': 'rs',
  'Sierra Leone': 'sl',
  Slovakia: 'sk',
  Slovenia: 'si',
  'South Africa': 'za',
  Spain: 'es',
  Suriname: 'sr',
  Sweden: 'se',
  Switzerland: 'ch',
  Syria: 'sy',
  'The Gambia': 'gm',
  Togo: 'tg',
  'Trinidad and Tobago': 'tt',
  Tunisia: 'tn',
  Türkiye: 'tr',
  Turkey: 'tr',
  Ukraine: 'ua',
  'United States': 'us',
  Uruguay: 'uy',
  Venezuela: 've',
  Wales: 'gb-wls',
  'Yugoslavia (Republic)': 'rs',
  Zaire: 'cd',
  Zambia: 'zm',
  Zimbabwe: 'zw',
};

export const FLAG_CDN_BASE = 'https://flagcdn.com';

// flagcdn.com only serves these fixed raster widths
const AVAILABLE_WIDTHS = [20, 40, 80, 160, 320, 640, 1280, 2560];

export function getCountryCode(nationality: string | undefined | null): string | undefined {
  if (!nationality) return undefined;
  return COUNTRY_CODES[nationality.trim()];
}

function nearestAvailableWidth(width: number): number {
  return AVAILABLE_WIDTHS.find((available) => available >= width) ?? AVAILABLE_WIDTHS[AVAILABLE_WIDTHS.length - 1];
}

export function getFlagUrl(nationality: string | undefined | null, width = 80): string | undefined {
  const code = getCountryCode(nationality);
  return code ? `${FLAG_CDN_BASE}/w${nearestAvailableWidth(width)}/${code}.png` : undefined;
}
